### ISSUE TITLE
Greetings from Pony.ai

### ISSUE THREAD

**Issue by yangtongxueruc** [jiegec/jiegec.github.io#1]

**Comment by yangtongxueruc** [comment]
Greetings from Pony.ai Campus Hiring Team!
We found you are our target candidate from Github. If you have interest in applying for [Pony.ai 2021 Campus Hiring](https://mp.weixin.qq.com/s/Owq0I7qA3Do5LYZY2z0itw) program, like Software Engineer or Hardware Engineer, we are here to help you get a Pony.ai offer!
You can just reply to [email](zhijie@pony.ai) with your resume and interested job and city. After your submission, we will share resources to help you grow technical skills and support you to get everything ready.
_(If you have completed your application, please ignore this email and thank you for your understanding)_
If you want to know more about us, please contact me via wechat "yangtongxueruc" or reply to this email.
You can also find more details via our website and feel free to let us know if you have any questions.

**Comment by jiegec** [comment]
?
